schema_org:
  alpha_creator:
    property: creator
    type: "http://schema.org/Person"
    value: name
  abstract:
    property: abstract
    type: "http://schema.org/Text"
    value: abstract
  description:
    property: description
    type: "http://schema.org/Text"
    value: description
  identifier:
    property: identifier
    type: "http://schema.org/URL"
    value: identifier
  issue_number:
    property: issueNumber
    value: issueNumber
